# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1976575ce822b91acafe1f8ec6dc59531440db9f85bd7ab5f8694b26a3ef5fd8b152664439b2590e14bf53853032cfdd5579b27ac5caef5c69f9c5f652700a9e

test:
  secret_key_base: a4fcb957b190f461fada1d8f5e0364c0fb9dc4c7896834efeff02da55e89932110e236131f54387386f4e2b27e277eb00f79c8e2ac60b45a7a902c996dd481bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
